$ErrorActionPreference = "Stop"

# Les variables PIPE_* restent en memoire dans un terminal PowerShell.
# Ce reset evite qu'un ancien test contamine le test suivant.
$names = @(
  "HOOK_XREFS",
  "BLAZE_OBSERVE_ONLY",
  "PIPE_FILL_SI",
  "PIPE_SEED_HOST",
  "PIPE_FILL_LIST",
  "PIPE_FORCE_HOST",
  "PIPE_FORCE_SECURE",
  "PIPE_FORCE_ADDR",
  "PIPE_FIX_TIMER",
  "PIPE_PING_OBS",
  "PIPE_CRASH_OBS",
  "PIPE_CRASH_FIX",
  "PIPE_RESOLVER_CLEAN_FIX",
  "PIPE_ORIGIN_ONLINE_FIX",
  "PIPE_ORIGIN_AUTHCODE_FIX",
  "PIPE_ORIGIN_VERSION_FIX",
  "PIPE_EBISU_FIX",
  "PIPE_STATUS_SLOT_POKE",
  "PIPE_STATUS_COMPLETE_POKE",
  "PIPE_STATUS_COMPLETE_IDX",
  "PIPE_STATUS_SLOT0_COMPLETE_POKE",
  "PIPE_CNNS_READY_POKE",
  "PIPE_LOGIN_STATE_POKE",
  "PIPE_LOGIN_STATE_SUCC_POKE",
  "PIPE_LOGIN_COMPLETE_CALL",
  "PIPE_LOGIN_RET_DONE_POKE",
  "PIPE_LOGIN_RET_DONE_VALUE",
  "PIPE_AUTO_DETACH_AFTER_LOGIN",
  "PIPE_AUTH_WAITER_DONE_POKE",
  "PIPE_AUTH_JOBQ_DONE_POKE",
  "PIPE_LOGIN_260_MAM",
  "PIPE_EXT_DISPATCH",
  "PIPE_ORPHAN_LISTENER",
  "PIPE_ORPHAN_STATIC_ONLY",
  "PIPE_ORPHAN_FN_ONLY",
  "PIPE_FAIL16",
  "PIPE_AUTH10_COMPLETE",
  "PIPE_JOB_BRIDGE",
  "PIPE_JOB_BRIDGE_MAM",
  "PIPE_WAITER_60",
  "PIPE_WAITER_SLOT5_RET_POKE",
  "PIPE_LOGIN_RET6_OBS",
  "PIPE_LOGIN_OUTFLAGS_OBS",
  "PIPE_LOGIN_OUTFLAGS_POKE",
  "PIPE_LOGIN_RSI_OUTFLAGS",
  "PIPE_SDB_UI"
)

foreach ($name in $names) {
  Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue
}

Write-Host "Pipeline env reset: $($names.Count) variables cleared"
